"""empty message

Revision ID: 25b0ee4fa0e
Revises: 13854b0f1f3
Create Date: 2015-01-29 13:42:46.253354

"""

# revision identifiers, used by Alembic.
revision = '25b0ee4fa0e'
down_revision = '13854b0f1f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
