"""empty message

Revision ID: 274f90f809
Revises: None
Create Date: 2015-01-27 22:36:04.081290

"""

# revision identifiers, used by Alembic.
revision = '274f90f809'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
