"""empty message

Revision ID: 2be02bbc2b8
Revises: 15d86280e1d
Create Date: 2015-01-30 16:23:13.080142

"""

# revision identifiers, used by Alembic.
revision = '2be02bbc2b8'
down_revision = '15d86280e1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
