"""empty message

Revision ID: 3256a12551
Revises: 25b0ee4fa0e
Create Date: 2015-01-29 14:28:01.365574

"""

# revision identifiers, used by Alembic.
revision = '3256a12551'
down_revision = '25b0ee4fa0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
