"""empty message

Revision ID: 40516f102ac
Revises: 3ee2c358bde
Create Date: 2015-01-29 16:36:36.921778

"""

# revision identifiers, used by Alembic.
revision = '40516f102ac'
down_revision = '3ee2c358bde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
